easy_admin:
    site_name: 'Backend timetable <p>test</p>'
    user:
        display_name: true
        display_avatar: true
    design:
        # all kinds of assets are supported and linked accordingly
        assets:
            favicon: '/assets/backend/favicon.png'
            css:
                - ''
            js:
                - ''
    entities:
        # List the entity class name you want to manage
        University:
            class: App\Entity\University
            label: 'Universities'
            list:
                title: '%%entity_name%% list'
                fields: ['id', {property: 'enable', label: 'Status'}, 'name', {property: 'name_full', label: 'Full name'}, 'faculties', 'buildings']
            show:
                fields: ['id', {property: 'enable', label: 'Status'}, 'name', {property: 'name_full', label: 'Full name'}, 'faculties', 'buildings']
            edit:
                fields: ['id', {property: 'enable', label: 'Status'}, 'name', {property: 'name_full', label: 'Full name'}]
            search:
                fields: ['id']
        Faculty:
            class: App\Entity\Faculty
            label: 'Faculties'
            list:
                title: '%%entity_name%% list'


#        - App\Entity\Party
#        - App\Entity\Schedule
#        - App\Entity\Course
#        - App\Entity\Teacher
#        - App\Entity\TeacherPosition
#        - App\Entity\Week
#        - App\Entity\LessonType
#        - App\Entity\Building
#        - App\Entity\Cabinet
#        - App\Entity\User
