easy_admin:
    entities:
        Course:
            class: 'App\Entity\Course'
            controller: 'App\Controller\EasyAdmin\CourseController'
            label: 'Course'
            list:
                title: 'Course list'
                sort: ['university', 'ASC']
                filters: ['university']
                fields: ['course', { property: 'name_full', label: 'Full name' }, 'university', 'parties']
                actions:
                    - { name: 'new', label: 'Add course' }
                    - { name: 'show', icon: 'eye', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash-alt', label: false }
            form:
                fields:
                    - { property: 'university', type_options: { required: true }, help: 'Choose university'}
                    - { property: 'course', type_options: { required: true }, help: 'Set course as number (1, 2, 5)' }
                    - { property: 'name_full', label: 'Full name', help: 'Set full name (First course, Second course)' }
            new:
                title: 'Create course'
            edit:
                title: 'Edit course'
                actions: ['-delete']
            show:
                title: 'Course view'
                fields:
                    - { type: 'group-1', label: 'Basic information', 'css_class':'col-md-6' }
                    - { property: 'course', 'type_options':{'block_name': 'group-1'} }
                    - { property: 'name_full', label: 'Full name', 'type_options':{'block_name': 'group-1'} }

                    - { type: 'group-2', label: 'Related data', 'css_class':'col-md-6' }
                    - { property: 'university', 'type_options':{'block_name': 'group-2'} }
                    - { property: 'parties', 'type_options':{'block_name': 'group-2'} }
                actions: ['-delete']