easy_admin:
    entities:
        Day:
            class: 'App\Entity\Day'
            controller: 'App\Controller\EasyAdmin\DayController'
            label: 'Day'
            list:
                title: 'Days list'
                sort: ['id', 'ASC']
                fields: ['name', { property: 'name_full', label: 'Full name' }]
                actions:
                    - { name: 'new', label: 'Add day' }
                    - { name: 'show', icon: 'eye', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash-alt', label: false }
            form:
                fields:
                    - { property: 'name', help: 'Set day abbreviation (Mo, Tu)'}
                    - { property: 'name_full', label: 'Full name', help: 'Set full name (Monday, Tuesday)' }
            new:
                title: 'Create day'
                fields: ['name', { property: 'name_full', label: 'Full name' }]
            edit:
                title: 'Edit day'
                fields: ['name', { property: 'name_full', label: 'Full name' }]
                actions: ['-delete']
            show:
                title: 'Day view'
                fields:
                    - { type: 'group-1', label: 'Basic information', 'css_class':'col-12' }
                    - { property: 'name', 'type_options':{'block_name': 'group-1'} }
                    - { property: 'name_full', label: 'Full name', 'type_options':{'block_name': 'group-1'} }

#                    - { type: 'group-2', label: 'Related data', 'css_class':'col-md-6' }
#                    - { property: 'schedules', 'type_options':{'block_name': 'group-2'} }
                actions: ['-delete']