easy_admin:
    entities:
        LessonType:
            class: 'App\Entity\LessonType'
            controller: 'App\Controller\EasyAdmin\LessonTypeController'
            label: 'Lesson types'
            list:
                title: 'Lesson types list'
                sort: ['id', 'ASC']
                fields: ['name', { property: 'name_full', label: 'Full name'}]
                actions:
                    - { name: 'new', label: 'Add type' }
                    - { name: 'show', icon: 'eye', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash-alt', label: false }
            form:
                fields:
                    - { property: 'name', help: 'Set short name (lec, pr)'}
                    - { property: 'name_full', label: 'Full name', help: 'Set full name (Lecture, Practice)' }
            new:
                title: 'Create lesson type'
            edit:
                title: 'Edit lesson type'
                actions: ['-delete']
            show:
                title: 'Lesson type view'
                fields:
                    - { type: 'group-1', label: 'Basic information', 'css_class':'col-md-6' }
                    - { property: 'name', 'type_options':{'block_name': 'group-1'} }
                    - { property: 'name_full', label: 'Full name', 'type_options':{'block_name': 'group-1'} }

                    - { type: 'group-2', label: 'Related data', 'css_class':'col-md-6' }
                    - { property: 'schedules', 'type_options':{'block_name': 'group-2'} }
                actions: ['-delete']