easy_admin:
    entities:
        Party:
            class: App\Entity\Party
            controller: App\Controller\EasyAdmin\PartyController
            label: 'Group'
            list:
                title: 'Party list'
                sort: ['course', 'ASC']
                filters: ['faculty', 'course']
                fields:
                    - 'name'
                    - 'course'
                    - 'faculty'
                    - 'schedules'
                actions:
                    - { name: 'new', label: 'Add party' }
                    - { name: 'show', icon: 'eye', label: false }
                    - { name: 'edit', icon: 'pencil', label: false, permission: 'ROLE_ADMIN'  }
                    - { name: 'delete', icon: 'trash-alt', label: false }
            form:
                fields:
                    - { property: 'faculty',  type_options: { required: true }, help: 'Choose faculty' }
                    - { property: 'course', type_options: { required: true }, help: 'Choose course' }
                    - { property: 'name',  help: 'Set group name (GN-2-1, GN-5-1m, GN-3-1tec)' }
            new:
                title: 'Create group'
            edit:
                title: 'Edit group'
                actions: ['-delete']
            show:
                title: 'Group view'
                fields:
                    - { type: 'group-1', label: 'Basic information', 'css_class':'col-md-6' }
                    - { property: 'name', 'type_options':{'block_name': 'group-1'} }
                    - { property: 'course', 'type_options':{'block_name': 'group-1'} }

                    - { type: 'group-2', label: 'Related data', 'css_class':'col-md-6' }
                    - { property: 'faculty', 'type_options':{'block_name': 'group-2'} }
                    - { property: 'schedules', 'type_options':{'block_name': 'group-2'} }
                actions: ['-delete']