easy_admin:
    entities:
        Time:
            class: 'App\Entity\UniversityTime'
            controller: 'App\Controller\EasyAdmin\UniversityTimeController'
            label: 'Class time'
            list:
                title: 'Class time list'
                sort: ['university', 'ASC']
                filters: ['university']
                fields:
                    - { property: 'name', label: 'Label'}
                    - { property: 'timeFrom', label: 'Start'}
                    - { property: 'timeTo', label: 'End'}
                    - { property: 'university'}
                    - { property: 'schedules'}
                actions:
                    - { name: 'new', label: 'Add class time' }
                    - { name: 'show', icon: 'eye', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash-alt', label: false }
            form:
                fields:
                    - { property: 'university',  type_options: { required: true }, help: 'Choose university' }
                    - { property: 'timeFrom', label: 'Start', help: 'Set class time start'  }
                    - { property: 'timeTo', label: 'End', help: 'Set class time end' }
            new:
                title: 'Create class time'
            edit:
                title: 'Edit class time'
                actions: ['-delete']
            show:
                title: 'Class time view'
                fields:
                    - { type: 'group-1', label: 'Basic information', 'css_class':'col-md-6' }
                    - { property: 'name',  label: 'Label',  'type_options':{'block_name': 'group-1'} }
                    - { property: 'timeFrom', label: 'Start','type_options':{'block_name': 'group-1'} }
                    - { property: 'timeTo', label: 'End', 'type_options':{'block_name': 'group-1'} }

                    - { type: 'group-2', label: 'Related data', 'css_class':'col-md-6' }
                    - { property: 'university', 'type_options':{'block_name': 'group-2'} }
                    - { property: 'schedules', 'type_options':{'block_name': 'group-2'} }
                actions: ['-delete']