easy_admin:
    entities:
        Week:
            class: 'App\Entity\Week'
            controller: 'App\Controller\EasyAdmin\WeekController'
            label: 'Weeks'
            list:
                title: 'Weeks list'
                sort: ['university', 'ASC']
                filters: ['university']
                fields: ['name', 'university', 'schedules']
                actions:
                    - { name: 'new', label: 'Add week' }
                    - { name: 'show', icon: 'eye', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash-alt', label: false }
            form:
                fields:
                    - { property: 'university', type_options: { required: true }, help: 'Choose university'}
                    - { property: 'name',  help: 'Set full name (First week, Second week)' }
            new:
                title: 'Create week'
            edit:
                title: 'Edit week'
            show:
                title: 'Week view'
                fields:
                    - { type: 'group-1', label: 'Basic information', 'css_class':'col-md-6' }
                    - { property: 'name', 'type_options':{'block_name': 'group-1'} }

                    - { type: 'group-2', label: 'Related data', 'css_class':'col-md-6' }
                    - { property: 'university', 'type_options':{'block_name': 'group-2'} }
                    - { property: 'schedules', 'type_options':{'block_name': 'group-2'} }
                actions: ['-delete']